Routes all oppgaver to smregistrering
navikt/syfosmpapirmottak pull request #82
Opened 2020-12-07 14:07 UTC by sebdak

Fjerner restriksjon på at kun pilotkontor mottar oppgaver i smregistrering

2020-12-07 14:19 UTC, andreasDev approved these changes

2020-12-07 15:33 UTC, tiasg commented
Todo: teste i Q

2020-12-08 06:35 UTC, tiafiring commented on src/main/kotlin/no/nav/syfo/service/SykmeldingService.kt
> +        log.info("Ruter oppgaven til smregistrering")
Her har visst loggingmeta falt ut

2020-12-08 06:39 UTC, tiafiring commented on src/test/kotlin/no/nav/syfo/service/SykmeldingServiceSpek.kt
> +        it("Send til smregistrering hvis henting av dokument (OCR) feiler") {
Lenger ned har vi en test som sier at det skal opprettes journalføringsoppgave hvis henting av dokument feiler eller hvis dokumentid er blank. Hvorfor skal vi da sende til smreg hvis henting av dokument feiler i dette tilfellet..? Hva er det vi egentlig ønsker oss at skal skje rent funksjonelt her?

2020-12-08 06:40 UTC, tiafiring requested changes
Det er uklart hva som egentlig skal skje funksjonelt sett, se kommentar på testklasse.

2020-12-08 08:27 UTC, tiasg commented on src/main/kotlin/no/nav/syfo/service/SykmeldingService.kt
> +        log.info("Ruter oppgaven til smregistrering")
Ups!

2020-12-08 09:00 UTC, tiasg commented on src/test/kotlin/no/nav/syfo/service/SykmeldingServiceSpek.kt
> +        it("Send til smregistrering hvis henting av dokument (OCR) feiler") {
Good catch. Vi endrer litt på testen nå, den er ikke riktig forklart eller utført.

Tanken ang. flyt er som følger:

- Hvis dokumentInfoId = null -> Opprett journalføringsoppgave
- Hvis Saf returnerer 404 -> Opprett journalføringsoppgave
- Hvis Saf returnerer 500 -> Send til Smreg, det kan ha vært midlertidig hikke. Hvis den ikke lar seg hente der heller vil det bli opprett journalføringsoppgave i Gosys og oppgaven sendes ut fra smreg igjen.

Hva tenker du, @tiafiring ?

2020-12-08 11:40 UTC, tiafiring approved these changes
👏

2020-12-08 11:42 UTC, sebdak commented
> 👏

Så ikke at du nettopp skrev denne. så du kan se bort ifra at jeg requesta nytt review fra deg 😄

2020-12-08 12:35 UTC, merged